
ARENA_SCRIPT_PATH=$(realpath $0)
ARENA_APP_TEMPLATE_DIR=$(dirname $ARENA_SCRIPT_PATH)

# Reemplazos
APP_NAME=$1
ARENA_FRONTEND_REPOSITORY=${ARENA_APP_TEMPLATE_DIR}/arena-frontend
ARENA_BACKEND_REPOSITORY=${ARENA_APP_TEMPLATE_DIR}/arena-backend

mkdir $ARENA_APP_TEMPLATE_DIR/$APP_NAME

cp -r $ARENA_APP_TEMPLATE_DIR/bash/templates/projects/app-frontend $ARENA_APP_TEMPLATE_DIR/$APP_NAME/$APP_NAME-frontend
cp -r $ARENA_APP_TEMPLATE_DIR/bash/templates/projects/app-backend $ARENA_APP_TEMPLATE_DIR/$APP_NAME/$APP_NAME-backend

grep -rl {APP_NAME} $ARENA_APP_TEMPLATE_DIR/$APP_NAME | xargs sed -i -e "s/{APP_NAME}/$APP_NAME/g" 
grep -rl {ARENA_FRONTEND_REPOSITORY} $ARENA_APP_TEMPLATE_DIR/$APP_NAME | xargs sed -i -e "s/{ARENA_FRONTEND_REPOSITORY}/'${ARENA_FRONTEND_REPOSITORY//\//\\/}'/g" 
grep -rl {ARENA_BACKEND_REPOSITORY} $ARENA_APP_TEMPLATE_DIR/$APP_NAME | xargs sed -i -e "s/{ARENA_BACKEND_REPOSITORY}/'${ARENA_BACKEND_REPOSITORY//\//\\/}'/g" 
