
CREATE TABLE IF NOT EXISTS PUBLIC.APPOINTMENT(ID BIGINT NOT NULL PRIMARY KEY,APPOINTMENT_DATE TIMESTAMP,ESTATE_TYPE INTEGER,OPERATION INTEGER,STATUS INTEGER,PLACE_ID BIGINT,USER_ID BIGINT);
CREATE TABLE IF NOT EXISTS PUBLIC.ASSESSMENT(ID BIGINT NOT NULL PRIMARY KEY,ESTATE_TYPE INTEGER,OPERATION INTEGER,SUGESTED_VALUE DOUBLE,PLACE_DESCRIPTION BIGINT,PLACE_ID BIGINT,USER_ID BIGINT);
CREATE TABLE IF NOT EXISTS PUBLIC.ESTATE(ID BIGINT NOT NULL,ESTATE_TYPE INTEGER,OPERATION INTEGER,PRICE BIGINT,STATUS INTEGER,OWNER BIGINT,PLACE_DESCRIPTION BIGINT NOT NULL PRIMARY KEY,PLACE_ID BIGINT)
CREATE TABLE IF NOT EXISTS PUBLIC.ESTATE_SEARCH(ID BIGINT NOT NULL PRIMARY KEY,ENVIRONMENTS INTEGER);
CREATE TABLE IF NOT EXISTS PUBLIC.OWNER(ID BIGINT NOT NULL PRIMARY KEY,ADDRESS BIGINT,CUIT BIGINT,DNI BIGINT,USER BIGINT,CONSTRAINT UK_N5GQP9FJVTU01Y0AIEIH0KY7V UNIQUE(USER))
CREATE TABLE IF NOT EXISTS PUBLIC.PHOTO(ID BIGINT NOT NULL PRIMARY KEY,PLACE BIGINT,VIEW VARCHAR(16777216));
CREATE TABLE IF NOT EXISTS PUBLIC.PLACE(ID BIGINT NOT NULL PRIMARY KEY,FLOOR INTEGER,FORMATTED_ADDRESS VARCHAR(255),UNIT VARCHAR(255));
CREATE TABLE IF NOT EXISTS PUBLIC.PLACE_DESCRIPTION(ID BIGINT NOT NULL PRIMARY KEY,CAR_PLACES INTEGER,COVERED_GARAGE BOOLEAN,ELECTRICITY BOOLEAN,ENVIRONMENTS INTEGER,EXTRA_NOTES VARCHAR(255),GAS BOOLEAN,LAUNDRY BOOLEAN,SEWER_CONNECTION BOOLEAN,SQUARE_METER_COVERED INTEGER,SQUARE_METER_TOTAL INTEGER,TOILETE BOOLEAN,TOILETS INTEGER,WATER_NETWORK_CONNECTION BOOLEAN);
CREATE TABLE IF NOT EXISTS PUBLIC.USER(ID BIGINT NOT NULL PRIMARY KEY,EMAIL VARCHAR(255),NAME VARCHAR(255),PHONE VARCHAR(255),STATUS INTEGER);
